# Generated by Django 5.1 on 2024-09-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_saleorder_saleorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderitem',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='SaleOrder',
        ),
        migrations.DeleteModel(
            name='SaleOrderItem',
        ),
    ]
