# Generated by Django 5.1 on 2024-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_saleorder_saleorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_address',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
