# Generated by Django 4.0.1 on 2024-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_saleorder_customer_remove_saleorderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='None'),
        ),
    ]
