# Generated by Django 4.0.1 on 2024-09-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_purchaseorder_remove_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='None'),
        ),
    ]
