# Generated by Django 4.0.1 on 2024-09-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_vendor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery_date',
        ),
    ]
