# Generated by Django 4.0.1 on 2024-09-15 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_purchaseorder_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
