# Generated by Django 4.0.1 on 2024-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_purchaseorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(max_length=255),
        ),
    ]
