# Generated by Django 4.0.1 on 2024-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_purchaseorder_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
