# Generated by Django 5.1 on 2024-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customer_city_customer_pincode_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='customer_city',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_pincode',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_state',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
