# Generated by Django 5.1.1 on 2024-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_category_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='name',
        ),
    ]
