# Generated by Django 5.1 on 2024-09-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_company_phone_number_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='user',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='user',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
