# Generated by Django 5.1 on 2024-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_purchaseorderitem_user_saleorderitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
